### ISSUE TITLE
Changelog TODO

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe#11072]
I've just updated the changelog to the best of my abilities: https://github.com/HaxeFoundation/haxe/commit/8c369e3be0bbabc2dfbca0c68bf2e90b60c4d186

Some TODOs:

* [x] @kLabz Could you diff Context/Compiler (and maybe something else I'm forgetting in std) and see what we added there? I noticed quite a few commits related to this and didn't want to add an entry for everything.

* [x] @kLabz Also, please apply some sorting at the end.

* [x] @RblSb Could you check if I missed one of your contributions? There were quite a few (thanks!), but some of it was minor stuff which I skipped.

* [x] @tobil4sk Same situation!

* [x] @Aidan63 Did I catch all important cpp changes?

* [ ] @ncannasse For HL I only added "hl : fixed various code generation problems". Is there anything in particular we should mention here?

* [ ] (?) I feel like I missed some things for the lua target in particular, maybe someone could check that (@sebthom perhaps)

* [x] Set the date to 2023

I also noticed a distinct lack of "js" entries, but I suppose the target is just that stable by now.

**Comment by Aidan63** [comment]
I think the other big cpp change is `haxe.Int64` handling, which comes with two main improvements.

- haxe.Int64's are no longer boxed when used in arrays or as map values.
- Maps with haxe.Int64 keys are now compared by value, not reference, so they work as you'd initially expect.

**Comment by Aidan63** [comment]
Ah, another thing I did was add support for non blocking exit codes with the Process API.

**Comment by tobil4sk** [comment]
> @tobil4sk Same situation!

There were these ones:

- Made sure there is a consistent way to unset environment variables: #10402
- Fixed Sys.environment behaviour across targets: #10460, #10464
- A bit less noteworthy, but also a few minor fixes to make -D flags with dashes/underscores work more consistently: #10365

**Comment by RblSb** [comment]
I don't remember much, but all important things from me seem to be mentioned.

**Comment by kLabz** [comment]
> I think the other big cpp change is `haxe.Int64` handling, which comes with two main improvements.
> 
>     * haxe.Int64's are no longer boxed when used in arrays or as map values.
> 
>     * Maps with haxe.Int64 keys are now compared by value, not reference, so they work as you'd initially expect.

@Aidan63 are both of these from #9935 ?

**Comment by Aidan63** [comment]
Yep, both from that merge.
