### ISSUE TITLE
Things to fix for 4.0.1

### ISSUE THREAD

**Issue by RealyUniqueName** [HaxeFoundation/haxe#8922]
- [x] git dependencies in haxelib.json https://github.com/HaxeFoundation/haxelib/issues/476
- [x] TType is erased sometimes https://github.com/HaxeFoundation/haxe/issues/8919 (not sure this is feasible for 4.0.1, but it's a regression)
- [x] `haxelib run --global` runs local copy of a lib https://github.com/HaxeFoundation/haxelib/issues/481
- [x] hide lua's BaseString from API docs https://github.com/HaxeFoundation/haxe/pull/8925

**Comment by CrazyFlasher** [comment]
Hi. It's marked as fixed. Whrn it will be released together with haxe? With 4.0.1 version?

**Comment by Gama11** [comment]
That's literally the issue title, yes. ;)

**Comment by Simn** [comment]
Cherry-picked https://github.com/HaxeFoundation/haxe/commit/fe493e8bd38b2e008109bcd4e63454ca702d30c1
